const data = {
    city: {
        country: 'France',
        state: 'Paris',
        city: 'Paris',
        aqi: 2,
        dirtRange: 'Moderate',
        pollution: {
            co: 315.67,
            no: 0.08,
            no2: 0.67,
            o3: 25.81,
            so2: 0.32,
            pm2_5: 2.19,
            pm10: 3.74,
            nh3: 0.41,
        },
        weather: {
            temp: 284.72,
            hu: 61,
            ws: 2.2,
            icon: '02d',
        },
    },
    otherCities: [
        {
            city: 'Tokyo',
            aqi: 3,
            dirtRange: 'Unhealthy for Sensitive Groups',
            pollution: {
                co: 385.42,
                no: 0.02,
                no2: 0.19,
                o3: 18.36,
                so2: 0.23,
                pm2_5: 3.09,
                pm10: 4.78,
                nh3: 0.09,
            },
            weather: {
                temp: 297.88,
                hu: 57,
                ws: 2.5,
                icon: '10d',
            },
        },
    ],
    isLoading: false,
    error: 'Data not available',
    clickedCity: {
        city: 'New York',
        aqi: 2,
        dirtRange: 'Moderate',
        pollution: {
            co: 320.75,
            no: 0.03,
            no2: 0.22,
            o3: 29.47,
            so2: 0.14,
            pm2_5: 2.35,
            pm10: 3.21,
            nh3: 0.07,
        },
        weather: {
            temp: 279.55,
            hu: 68,
            ws: 1.85,
            icon: '03d',
        },
    },
    selectedCities: [
        {
            city: 'Sydney',
            aqi: 2,
            dirtRange: 'Moderate',
            pollution: {
                co: 312.91,
                no: 0.05,
                no2: 0.28,
                o3: 31.74,
                so2: 0.18,
                pm2_5: 2.01,
                pm10: 3.52,
                nh3: 0.11,
            },
            weather: {
                temp: 302.11,
                hu: 53,
                ws: 2.02,
                icon: '02d',
            },
        },
    ],
    selectedCity: {
        city: 'Rio de Janeiro',
        aqi: 3,
        dirtRange: 'Unhealthy for Sensitive Groups',
        pollution: {
            co: 400.39,
            no: 0.07,
            no2: 0.42,
            o3: 15.97,
            so2: 0.27,
            pm2_5: 3.45,
            pm10: 5.13,
            nh3: 0.14,
        },
        weather: {
            temp: 299.14,
            hu: 70,
            ws: 2.8,
            icon: '09d',
        },
    },
};

export default data;
